### ISSUE TITLE
hello詢問是否能提供OpenNRE所需的四個json檔案

### ISSUE THREAD

**Issue by Jim0530** [Pelhans/Z_knowledge_graph#1]
您好我想像您詢問是否能提供OpenNRE的四個json檔案，想試著跑跑看OpenNRE在中文上運行的狀況

**Comment by Pelhans** [comment]
这个是在我服务器上存着的，下载速度比较慢，你先试试106.13.45.76:8080/baidu_6w.tar.gz

**Comment by Pelhans** [comment]
百度云盘的 链接：https://pan.baidu.com/s/1u5ztCn1RHU2zSuYduI7uqw 提取码：iflx

**Comment by geekboood** [comment]
> 百度云盘的 链接：https://pan.baidu.com/s/1u5ztCn1RHU2zSuYduI7uqw 提取码：iflx

@Pelhans 
链接失效了，能再发一下吗。。

**Comment by Pelhans** [comment]
链接：https://pan.baidu.com/s/1mEps1ThlqOKcEnDy5AEysA 
提取码：97sp
