### ISSUE TITLE
关于爬虫的结果文件方不方便提供一下啊

### ISSUE THREAD

**Issue by 1157354** [Pelhans/Z_knowledge_graph#4]
谢谢

**Comment by Pelhans** [comment]
百度百科和互动百科的 sql 文件，百度的 400 多万，互动的只有 100 多万（最早的 400 多万的丢了，再爬只弄到 100 多，以后再更新）
链接：https://pan.baidu.com/s/11lkOtbivwuXotL8WB01scw 
提取码：ccf3
